// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDA0BqEW5zf2rP_zKmiRZtsDOJhGNoatoU',
    appId: '1:69853997439:web:1e1329a4eded162969524a',
    messagingSenderId: '69853997439',
    projectId: 'flutterprj-6a249',
    authDomain: 'flutterprj-6a249.firebaseapp.com',
    storageBucket: 'flutterprj-6a249.firebasestorage.app',
    measurementId: 'G-2EX38W87GR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgkTF9yv4pYiun5dOFBRgZUexWzTp_cbg',
    appId: '1:69853997439:android:7d5c2236bcd58c9f69524a',
    messagingSenderId: '69853997439',
    projectId: 'flutterprj-6a249',
    storageBucket: 'flutterprj-6a249.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjWb-JIBN7UWHaN75JbfYdANs81hejQAA',
    appId: '1:69853997439:ios:e5ae317067cabdc469524a',
    messagingSenderId: '69853997439',
    projectId: 'flutterprj-6a249',
    storageBucket: 'flutterprj-6a249.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAjWb-JIBN7UWHaN75JbfYdANs81hejQAA',
    appId: '1:69853997439:ios:e5ae317067cabdc469524a',
    messagingSenderId: '69853997439',
    projectId: 'flutterprj-6a249',
    storageBucket: 'flutterprj-6a249.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDA0BqEW5zf2rP_zKmiRZtsDOJhGNoatoU',
    appId: '1:69853997439:web:e0e5258aac68235769524a',
    messagingSenderId: '69853997439',
    projectId: 'flutterprj-6a249',
    authDomain: 'flutterprj-6a249.firebaseapp.com',
    storageBucket: 'flutterprj-6a249.firebasestorage.app',
    measurementId: 'G-9CH7EVVMQL',
  );
}
